### ISSUE TITLE
Error: Please run node with the --harmony flag!

### ISSUE THREAD

**Issue by moroshko** [alansouzati/gulp-jest#9] opened 2015-02-04 07:26 UTC
I get the following error when running `gulp test`:

```
Error: Please run node with the --harmony flag!
```

Here is my gulp task:

```
gulp.task('test', function() {
  return gulp.src('src/**/__tests__').pipe(jest({
    rootDir: 'src',
    scriptPreprocessor: '../node_modules/6to5-jest',
    unmockedModulePathPatterns: [ 'react' ]
  }));
});
```

To reproduce: https://github.com/SEEK-Jobs/react-playground

Note that `npm test` works properly (test is failing as expected), but `gulp test` fails with the error above. Both `npm test` and `gulp test` have the same config object:

```
{
  rootDir: 'src',
  scriptPreprocessor: '../node_modules/6to5-jest',
  unmockedModulePathPatterns: [ 'react' ]
}
```

What am I doing wrong?

**Comment by Dakuan** [comment] 2015-02-04 11:33
I think this is a gulp issue, see if https://github.com/gulpjs/gulp/issues/66 helps you

**Comment by mik01aj** [comment] 2015-02-11 14:17
I don't think this is a Gulp problem. Imho it's either `gulp-jest` or `jest` itself. Look at this:

![screenshot 2015-02-11 15 11 15](https://cloud.githubusercontent.com/assets/3027415/6148362/17f2ee04-b201-11e4-9094-dd5aa33a9b48.png)

**Comment by Dakuan** [comment] 2015-02-11 15:09
Have you seen this fix? http://stackoverflow.com/questions/28315796/why-gulp-jest-is-failing-with-please-run-node-with-the-harmony-flag

**Comment by mik01aj** [comment] 2015-02-11 16:05
Works great, thanks! But it would be nice to find the original cause of this, anyway :)

**Comment by Dakuan** [comment] 2015-02-11 16:17
Indeed - I'm not convinced that the issue is in `gulp-jest`.

Do you mind if I close this? @mik01aj @moroshko

**Comment by mik01aj** [comment] 2015-02-11 16:29
Yes. I suppose it's a bug in `jest-cli` and I will report it there.

![screenshot 2015-02-11 17 28 35](https://cloud.githubusercontent.com/assets/3027415/6151035/710cd9de-b213-11e4-8843-ced1ed35d9a6.png)

**Comment by Dakuan** [comment] 2015-02-23 18:22
I've shipped an update that includes the latest `jest-cli` which should resolve this for you. Let me know how you get on!

**Comment by binarykitchen** [comment] 2015-02-24 03:06
Still having the same issue, even with your latest version:

```
Error: Please run node with the --harmony flag! jest requires WeakMap which is only available with the --harmony flag in node < v0.12
```

**Comment by joshuacalloway** [comment] 2015-03-05 20:17
I'm seeing this error too.  tried adding this to my gulpfile
  require('harmonize')();

This works fine with my "grunt jest"

**Comment by ieugen** [comment] 2015-03-20 12:35
+1, please add to official docs/npm page

**Comment by moimikey** [comment] 2015-03-24 23:04
+1 for `require('harmonize')()`. not a blocker at all with it, but until they update the npm package with their latest patch, you'll lose your stdout colors =/

**Comment by ScreenDriver** [comment] 2015-05-29 07:21
+1 for `require('harmonize')()`

**Comment by binarykitchen** [comment] 2015-06-25 04:04
Since nothing happened, I took the liberty to fork it and make it compatible for the latest iojs: https://www.npmjs.com/package/gulp-jest-iojs

**Comment by alansouzati** [comment] 2016-09-02 00:14
Is this still an issue? I'm planning to maintain this library now. let me know if the latest version presents any issues.

**Comment by alansouzati** [comment] 2016-12-21 19:42
Closing this issue as there is not activity on it.

**Closed by alansouzati** 2016-12-21 19:42 UTC
